version: '3'

services:
  db:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    user: mysql
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/sample-data:/tmp/sample-data
      - ./db/container-init.sh:/tmp/container-init.sh
    restart: always
    ports:
      - 3306:3306